version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hirebot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hirebot_password}
      POSTGRES_DB: ${POSTGRES_DB:-hirebot_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  backend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.backend
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port ${BACKEND_PORT:-8000} --reload

volumes:
  db_data: